// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYXZ3AJLGnFxLRQg5pcn45J6yoLuO8AHI',
    appId: '1:273735040761:web:ad03d0c0632bb205756c28',
    messagingSenderId: '273735040761',
    projectId: 'spotify1224-70ae0',
    authDomain: 'spotify1224-70ae0.firebaseapp.com',
    storageBucket: 'spotify1224-70ae0.appspot.com',
    measurementId: 'G-HE9PSK5ZTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq3-Sw8rpgsrQRhpL8P2Mmv6bqNbGjgpo',
    appId: '1:273735040761:android:ee9ecb7ae16bebd4756c28',
    messagingSenderId: '273735040761',
    projectId: 'spotify1224-70ae0',
    storageBucket: 'spotify1224-70ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBILoDr_2l8bzaFF1b2qWYIO5svFR-dbrM',
    appId: '1:273735040761:ios:9687852c187284e6756c28',
    messagingSenderId: '273735040761',
    projectId: 'spotify1224-70ae0',
    storageBucket: 'spotify1224-70ae0.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBILoDr_2l8bzaFF1b2qWYIO5svFR-dbrM',
    appId: '1:273735040761:ios:9687852c187284e6756c28',
    messagingSenderId: '273735040761',
    projectId: 'spotify1224-70ae0',
    storageBucket: 'spotify1224-70ae0.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYXZ3AJLGnFxLRQg5pcn45J6yoLuO8AHI',
    appId: '1:273735040761:web:07f6ca642b92da3d756c28',
    messagingSenderId: '273735040761',
    projectId: 'spotify1224-70ae0',
    authDomain: 'spotify1224-70ae0.firebaseapp.com',
    storageBucket: 'spotify1224-70ae0.appspot.com',
    measurementId: 'G-RDVKM42C30',
  );
}
